// --------------------------------------------------------------------------------------------------------------------
// <copyright file="FormSettings.Designer.cs" company="Dzakhov's jag">
//   Copyright © Dmitry Dzakhov 2013
// </copyright>
// <auto-generated />
// <summary>
//   Application settings.
// </summary>
// --------------------------------------------------------------------------------------------------------------------

namespace RoboConsole
{
    partial class FormSettings
    {
        /// <summary>
        /// Требуется переменная конструктора.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Освободить все используемые ресурсы.
        /// </summary>
        /// <param name="disposing">истинно, если управляемый ресурс должен быть удален; иначе ложно.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Код, автоматически созданный конструктором форм Windows

        /// <summary>
        /// Обязательный метод для поддержки конструктора - не изменяйте
        /// содержимое данного метода при помощи редактора кода.
        /// </summary>
        private void InitializeComponent()
        {
            this.groupBoxWiFi = new System.Windows.Forms.GroupBox();
            this.tableLayoutPanelWiFi = new System.Windows.Forms.TableLayoutPanel();
            this.labelIP = new System.Windows.Forms.Label();
            this.labelSendPort = new System.Windows.Forms.Label();
            this.textBoxSendPort = new System.Windows.Forms.TextBox();
            this.labelReceivePort = new System.Windows.Forms.Label();
            this.textBoxReceivePort = new System.Windows.Forms.TextBox();
            this.textBoxIP = new System.Windows.Forms.TextBox();
            this.groupBoxCOM = new System.Windows.Forms.GroupBox();
            this.tableLayoutPanelCOM = new System.Windows.Forms.TableLayoutPanel();
            this.label1 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.comboBoxComPort = new System.Windows.Forms.ComboBox();
            this.comboBoxBaudRate = new System.Windows.Forms.ComboBox();
            this.buttonOk = new System.Windows.Forms.Button();
            this.buttonCancel = new System.Windows.Forms.Button();
            this.groupBoxWiFi.SuspendLayout();
            this.tableLayoutPanelWiFi.SuspendLayout();
            this.groupBoxCOM.SuspendLayout();
            this.tableLayoutPanelCOM.SuspendLayout();
            this.SuspendLayout();
            // 
            // groupBoxWiFi
            // 
            this.groupBoxWiFi.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.groupBoxWiFi.Controls.Add(this.tableLayoutPanelWiFi);
            this.groupBoxWiFi.Location = new System.Drawing.Point(12, 12);
            this.groupBoxWiFi.Name = "groupBoxWiFi";
            this.groupBoxWiFi.Size = new System.Drawing.Size(266, 136);
            this.groupBoxWiFi.TabIndex = 0;
            this.groupBoxWiFi.TabStop = false;
            this.groupBoxWiFi.Text = "Соединение по Wi-Fi";
            // 
            // tableLayoutPanelWiFi
            // 
            this.tableLayoutPanelWiFi.ColumnCount = 4;
            this.tableLayoutPanelWiFi.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 10F));
            this.tableLayoutPanelWiFi.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanelWiFi.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanelWiFi.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 12F));
            this.tableLayoutPanelWiFi.Controls.Add(this.labelIP, 1, 1);
            this.tableLayoutPanelWiFi.Controls.Add(this.labelSendPort, 1, 3);
            this.tableLayoutPanelWiFi.Controls.Add(this.textBoxSendPort, 2, 3);
            this.tableLayoutPanelWiFi.Controls.Add(this.labelReceivePort, 1, 5);
            this.tableLayoutPanelWiFi.Controls.Add(this.textBoxReceivePort, 2, 5);
            this.tableLayoutPanelWiFi.Controls.Add(this.textBoxIP, 2, 1);
            this.tableLayoutPanelWiFi.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanelWiFi.Location = new System.Drawing.Point(3, 16);
            this.tableLayoutPanelWiFi.Name = "tableLayoutPanelWiFi";
            this.tableLayoutPanelWiFi.RowCount = 7;
            this.tableLayoutPanelWiFi.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 10F));
            this.tableLayoutPanelWiFi.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 25F));
            this.tableLayoutPanelWiFi.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 10F));
            this.tableLayoutPanelWiFi.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 25F));
            this.tableLayoutPanelWiFi.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 10F));
            this.tableLayoutPanelWiFi.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 25F));
            this.tableLayoutPanelWiFi.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 10F));
            this.tableLayoutPanelWiFi.Size = new System.Drawing.Size(260, 117);
            this.tableLayoutPanelWiFi.TabIndex = 0;
            // 
            // labelIP
            // 
            this.labelIP.AutoSize = true;
            this.labelIP.Dock = System.Windows.Forms.DockStyle.Fill;
            this.labelIP.Location = new System.Drawing.Point(13, 10);
            this.labelIP.Name = "labelIP";
            this.labelIP.Size = new System.Drawing.Size(113, 25);
            this.labelIP.TabIndex = 0;
            this.labelIP.Text = "IP робота";
            this.labelIP.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // labelSendPort
            // 
            this.labelSendPort.AutoSize = true;
            this.labelSendPort.Dock = System.Windows.Forms.DockStyle.Fill;
            this.labelSendPort.Location = new System.Drawing.Point(13, 45);
            this.labelSendPort.Name = "labelSendPort";
            this.labelSendPort.Size = new System.Drawing.Size(113, 25);
            this.labelSendPort.TabIndex = 2;
            this.labelSendPort.Text = "Порт передачи";
            this.labelSendPort.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // textBoxSendPort
            // 
            this.textBoxSendPort.CausesValidation = false;
            this.textBoxSendPort.Dock = System.Windows.Forms.DockStyle.Fill;
            this.textBoxSendPort.Location = new System.Drawing.Point(132, 48);
            this.textBoxSendPort.Name = "textBoxSendPort";
            this.textBoxSendPort.Size = new System.Drawing.Size(113, 20);
            this.textBoxSendPort.TabIndex = 3;
            // 
            // labelReceivePort
            // 
            this.labelReceivePort.AutoSize = true;
            this.labelReceivePort.Dock = System.Windows.Forms.DockStyle.Fill;
            this.labelReceivePort.Location = new System.Drawing.Point(13, 80);
            this.labelReceivePort.Name = "labelReceivePort";
            this.labelReceivePort.Size = new System.Drawing.Size(113, 25);
            this.labelReceivePort.TabIndex = 4;
            this.labelReceivePort.Text = "Порт приёма";
            this.labelReceivePort.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // textBoxReceivePort
            // 
            this.textBoxReceivePort.CausesValidation = false;
            this.textBoxReceivePort.Dock = System.Windows.Forms.DockStyle.Fill;
            this.textBoxReceivePort.Location = new System.Drawing.Point(132, 83);
            this.textBoxReceivePort.Name = "textBoxReceivePort";
            this.textBoxReceivePort.Size = new System.Drawing.Size(113, 20);
            this.textBoxReceivePort.TabIndex = 5;
            // 
            // textBoxIP
            // 
            this.textBoxIP.CausesValidation = false;
            this.textBoxIP.Dock = System.Windows.Forms.DockStyle.Fill;
            this.textBoxIP.Location = new System.Drawing.Point(132, 13);
            this.textBoxIP.Name = "textBoxIP";
            this.textBoxIP.Size = new System.Drawing.Size(113, 20);
            this.textBoxIP.TabIndex = 1;
            // 
            // groupBoxCOM
            // 
            this.groupBoxCOM.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.groupBoxCOM.Controls.Add(this.tableLayoutPanelCOM);
            this.groupBoxCOM.Location = new System.Drawing.Point(15, 166);
            this.groupBoxCOM.Name = "groupBoxCOM";
            this.groupBoxCOM.Size = new System.Drawing.Size(266, 100);
            this.groupBoxCOM.TabIndex = 1;
            this.groupBoxCOM.TabStop = false;
            this.groupBoxCOM.Text = "Соединение по COM-порту";
            // 
            // tableLayoutPanelCOM
            // 
            this.tableLayoutPanelCOM.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Zoom;
            this.tableLayoutPanelCOM.ColumnCount = 4;
            this.tableLayoutPanelCOM.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 10F));
            this.tableLayoutPanelCOM.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanelCOM.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanelCOM.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 12F));
            this.tableLayoutPanelCOM.Controls.Add(this.label1, 1, 1);
            this.tableLayoutPanelCOM.Controls.Add(this.label2, 1, 3);
            this.tableLayoutPanelCOM.Controls.Add(this.comboBoxComPort, 2, 1);
            this.tableLayoutPanelCOM.Controls.Add(this.comboBoxBaudRate, 2, 3);
            this.tableLayoutPanelCOM.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanelCOM.Location = new System.Drawing.Point(3, 16);
            this.tableLayoutPanelCOM.Name = "tableLayoutPanelCOM";
            this.tableLayoutPanelCOM.RowCount = 5;
            this.tableLayoutPanelCOM.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 10F));
            this.tableLayoutPanelCOM.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 25F));
            this.tableLayoutPanelCOM.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 10F));
            this.tableLayoutPanelCOM.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 25F));
            this.tableLayoutPanelCOM.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 10F));
            this.tableLayoutPanelCOM.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.tableLayoutPanelCOM.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.tableLayoutPanelCOM.Size = new System.Drawing.Size(260, 81);
            this.tableLayoutPanelCOM.TabIndex = 0;
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.label1.Location = new System.Drawing.Point(13, 10);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(113, 25);
            this.label1.TabIndex = 0;
            this.label1.Text = "COM-порт";
            this.label1.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Dock = System.Windows.Forms.DockStyle.Fill;
            this.label2.Location = new System.Drawing.Point(13, 45);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(113, 25);
            this.label2.TabIndex = 1;
            this.label2.Text = "Скорость порта";
            this.label2.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // comboBoxComPort
            // 
            this.comboBoxComPort.Dock = System.Windows.Forms.DockStyle.Fill;
            this.comboBoxComPort.FormattingEnabled = true;
            this.comboBoxComPort.Location = new System.Drawing.Point(132, 13);
            this.comboBoxComPort.Name = "comboBoxComPort";
            this.comboBoxComPort.Size = new System.Drawing.Size(113, 21);
            this.comboBoxComPort.TabIndex = 2;
            // 
            // comboBoxBaudRate
            // 
            this.comboBoxBaudRate.Dock = System.Windows.Forms.DockStyle.Fill;
            this.comboBoxBaudRate.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.comboBoxBaudRate.FormattingEnabled = true;
            this.comboBoxBaudRate.Location = new System.Drawing.Point(132, 48);
            this.comboBoxBaudRate.Name = "comboBoxBaudRate";
            this.comboBoxBaudRate.Size = new System.Drawing.Size(113, 21);
            this.comboBoxBaudRate.TabIndex = 3;
            // 
            // buttonOk
            // 
            this.buttonOk.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.buttonOk.CausesValidation = false;
            this.buttonOk.DialogResult = System.Windows.Forms.DialogResult.OK;
            this.buttonOk.Location = new System.Drawing.Point(123, 286);
            this.buttonOk.Name = "buttonOk";
            this.buttonOk.Size = new System.Drawing.Size(75, 23);
            this.buttonOk.TabIndex = 2;
            this.buttonOk.Text = "OK";
            this.buttonOk.UseVisualStyleBackColor = true;
            this.buttonOk.Click += new System.EventHandler(this.ButtonOkClick);
            // 
            // buttonCancel
            // 
            this.buttonCancel.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.buttonCancel.CausesValidation = false;
            this.buttonCancel.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this.buttonCancel.Location = new System.Drawing.Point(204, 286);
            this.buttonCancel.Name = "buttonCancel";
            this.buttonCancel.Size = new System.Drawing.Size(75, 23);
            this.buttonCancel.TabIndex = 3;
            this.buttonCancel.Text = "Отмена";
            this.buttonCancel.UseVisualStyleBackColor = true;
            // 
            // FormSettings
            // 
            this.AcceptButton = this.buttonOk;
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.CancelButton = this.buttonCancel;
            this.CausesValidation = false;
            this.ClientSize = new System.Drawing.Size(290, 318);
            this.Controls.Add(this.buttonCancel);
            this.Controls.Add(this.buttonOk);
            this.Controls.Add(this.groupBoxCOM);
            this.Controls.Add(this.groupBoxWiFi);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedDialog;
            this.MaximizeBox = false;
            this.Name = "FormSettings";
            this.ShowInTaskbar = false;
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "Настройки";
            this.Load += new System.EventHandler(this.FormSettingsLoad);
            this.groupBoxWiFi.ResumeLayout(false);
            this.tableLayoutPanelWiFi.ResumeLayout(false);
            this.tableLayoutPanelWiFi.PerformLayout();
            this.groupBoxCOM.ResumeLayout(false);
            this.tableLayoutPanelCOM.ResumeLayout(false);
            this.tableLayoutPanelCOM.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.GroupBox groupBoxWiFi;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanelWiFi;
        private System.Windows.Forms.Label labelIP;
        private System.Windows.Forms.Label labelSendPort;
        private System.Windows.Forms.TextBox textBoxSendPort;
        private System.Windows.Forms.Label labelReceivePort;
        private System.Windows.Forms.TextBox textBoxReceivePort;
        private System.Windows.Forms.GroupBox groupBoxCOM;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanelCOM;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Button buttonOk;
        private System.Windows.Forms.Button buttonCancel;
        private System.Windows.Forms.TextBox textBoxIP;
        private System.Windows.Forms.ComboBox comboBoxComPort;
        private System.Windows.Forms.ComboBox comboBoxBaudRate;
    }
}